#!/usr/bin/env python

import sys
import os
import re
import logging
import fnmatch

from argparse import ArgumentParser

parser = ArgumentParser(description = 'Dynamo')
parser.add_argument('--policy', '-p', metavar = 'FILE', dest = 'policy', required = True, help = 'Policy files.')
parser.add_argument('--config', '-c', metavar = 'CONFIG', dest = 'config', required = True, help = 'Configuration JSON.')
parser.add_argument('--comment', '-m', metavar = 'COMMENT', dest = 'comment', help = 'Comment to be sent to deletion interface as well as the local deletion record.')
parser.add_argument('--dry-run', '-D', action = 'store_true', dest = 'dry_run', help = 'Do not make any actual deletion requests or changes to inventory.')

args = parser.parse_args()
sys.argv = []

## Load the configuration
from dataformat.configuration import Configuration

config = Configuration(args.config)

## Set up logging (write to stdout)
log_level = getattr(logging, config.log_level.upper())
log_format = '%(asctime)s:%(levelname)s:%(name)s: %(message)s'

logging.basicConfig(level = log_level, format = log_format, stream = sys.stdout)
LOG = logging.getLogger()

LOG.info('Starting Detox.')

## Set up the detox policy
from detox.policy import Policy

with open(os.environ['DYNAMO_BASE'] + '/etc/policies.tag') as tag:
    policy_version = tag.read().strip()

with open(args.policy) as policy_def:    
    policy = Policy(policy_def, policy_version, inventory)

## Set up demand calculators
from demand.demand import DemandManager

demand_manager = DemandManager()

#for plugin in policy.used_demand_plugins:
#    if plugin not in demand_manager.calculators:
#        demand_manager.calculators[plugin] = classes.demand_plugins[plugin]()

## Run the main detox object
from core.executable import inventory
from detox.main import Detox

config.detox.deletion.phedex = config.phedex
config.detox.copy.phedex = config.phedex

detox = Detox(config)

detox.run(policy, inventory, demand_manager, comment = args.comment)
