#!/usr/bin/env python

import sys
import os
import re
import fnmatch

from argparse import ArgumentParser

parser = ArgumentParser(description = 'File operations manager.')
parser.add_argument('--config', '-c', metavar = 'CONFIG', dest = 'config', help = 'Configuration JSON.')

args = parser.parse_args()
sys.argv = []

## Load the configuration
from dynamo.dataformat.configuration import Configuration

config = Configuration(args.config)

## Set up logging (write to stdout)
from dynamo.core.executable import make_standard_logger, authorized

LOG = make_standard_logger(config.get('log_level', 'debug'))

## Configure
from dynamo.fileop.rlfsm import RLFSM
from dynamo.core.executable import inventory

## Run the main program
LOG.info('Instantiating RLFSM.')

rlfsm = RLFSM(config.get('rlfsm', None))

if not authorized:
    rlfsm.set_read_only()

LOG.info('Checking and executing new file transfer subscriptions.')
rlfsm.transfer_files(inventory)

LOG.info('Checking and executing new file deletion subscriptions.')
rlfsm.delete_files(inventory)
