#!/usr/bin/env python

###############################################################
####### This script will spit out png files monitoring ########
####### the copy status through Phedex on three levels: #######
####### -per replica, -per request, -per site #################
#
####### yiiyama@mit.edu, bmaier@mit.edu #######################
###############################################################

import sys
import os
import time
import shutil
import rrdtool
import selinux
import csv

from datetime import datetime, timedelta

from argparse import ArgumentParser

parser = ArgumentParser(description = 'Track enforcer rules')
parser.add_argument('--config', '-c', metavar = 'CONFIG', dest = 'config', required = True, help = 'Configuration JSON for dealermon-like programs.')

args = parser.parse_args()
sys.argv = []

from dynamo.dataformat import Configuration
from dynamo.core.executable import inventory, read_only, make_standard_logger
from dynamo.enforcer.interface import EnforcerInterface

## Configuration for steering tracking (intervals, output directories, etc)

config = Configuration(args.config)
dealer_config = Configuration(config.dealer_config).dealer

## Create an enforcer instance

enforcer_config = Configuration(dealer_config.plugins.enforcer.config.enforcer)
enforcer_config['write_rrds'] = True
enforcer = EnforcerInterface(enforcer_config)

## Logger

LOG = make_standard_logger(config.log_level)

## Paths

rrd_dir = config.rrd_path_base + '/track_enforcer'

if not read_only:
    try:
        os.makedirs(rrd_dir)
    except OSError:
        pass

## RRD functions

interval = int(config.rrd_interval)

def create_rrd(path):
    if read_only:
        return

    start = (int(time.time()) / interval - 1) * interval

    rrdtool.create(path, '--start', str(start), '--step', str(interval),
                   'DS:missing:GAUGE:%d:0:U' % (interval * 800),
                   'DS:there:GAUGE:%d:0:U' % (interval * 800),
                   'RRA:LAST:0:1:%i' % 28400)

    # data source
    #  DS:<name>:<type>:<heartbeat>:<min>:<max>
    #  type = GAUGE: quantity that has a value at each time point
    #  heartbeat: "maximum number of seconds that may pass between two updates of this
    #              data source before the value of the data source is assumed to be *UNKNOWN*"
    #  min/max = U: unknown
    # round robin archive (RRA)
    #  RRA:<type>:<xff>:<nsteps>:<nrows>
    #  type = LAST: just use the last value, no averaging etc.
    #  xff: fraction of <nsteps> that can have UNKNOWN as the value
    #  nsteps: number of steps used for calculation
    #  nrows: number of records to keep

    # change selinux context of the RRD so that it can be read by a apache-invoked PHP script
    try:
        selinux.chcon(path, 'unconfined_u:object_r:httpd_sys_content_t:s0')
    except:
        pass

## Get all enforcer rules' statuses

rrd_info = enforcer.report_back(inventory)

for rule_name, already_there, still_missing in rrd_info:
    
    rrd_file = '%s/%s.rrd' % (rrd_dir, rule_name)

    if not read_only and not os.path.exists(rrd_file):
        # RRD does not exist yet                                                                                                                                                         
        create_rrd(rrd_file)

    # Update the RRD file
    timestamp = int(time.time()) / interval * interval

    try:
        lasttime = rrdtool.fetch(rrd_file, "LAST")[0][1]
    except:
        lasttime = 0
            
    if not read_only and timestamp != lasttime:
        rrdtool.update(rrd_file, '%d:%i:%i' % (timestamp, still_missing, already_there))

if not read_only:
    target_dir = config.rrd_publish_target + '/monitoring_enforcer'
    
    try:
        os.makedirs(target_dir)
    except OSError:
        pass
    
    for entry in os.listdir(rrd_dir):
        if entry.endswith('.rrd'):
            shutil.copy(rrd_dir + '/' + entry, target_dir + '/' + entry)
