#!/usr/bin/env python

import sys
from argparse import ArgumentParser

parser = ArgumentParser(description = 'Update site status.')
parser.add_argument('--config', '-c', metavar = 'CONFIG', dest = 'config', required = True, help = 'Configuration JSON.')

args = parser.parse_args()
sys.argv = []

## Load the configuration
from dynamo.dataformat import Configuration

config = Configuration(args.config)

## Set up logging (write to stdout)
from dynamo.core.executable import make_standard_logger

LOG = make_standard_logger(config.log_level)

## Load and initialize sources
from dynamo.core.executable import inventory
import dynamo.source.impl as sources

config.sites.config.phedex = config.phedex

site_source = sources.PhEDExSiteInfoSource(config.sites.config)

## Start the update
from dynamo.utils.parallel import Map

def set_status(site):
    LOG.info('Updating %s', site.name)
    site.status = site_source.get_site_status(site.name)
    LOG.info('Status: %d', site.status)

sites = site_source.get_site_list()
Map().execute(set_status, sites)

for site in sites:
    inventory.update(site)

LOG.info('Site update completed.')
