#!/usr/bin/env python

import sys
import logging
from argparse import ArgumentParser

parser = ArgumentParser(description = 'Update dataset popularity.')
parser.add_argument('--config', '-c', metavar = 'CONFIG', dest = 'config', required = True, help = 'Configuration JSON.')

args = parser.parse_args()
sys.argv = []

## Load the configuration
from dynamo.dataformat import Configuration

config = Configuration(args.config)

config.crabaccess.store = config.mysql
config.globalqueue.store = config.mysql

## Set up logging (write to stdout)
from dynamo.core.executable import make_standard_logger

LOG = make_standard_logger(config.log_level)

## Load the inventory
from dynamo.core.executable import inventory

## Update: CRABAccessHistory

LOG.info('Updateing CRABAccessHistory.')

from dynamo.policy.producers.crabaccess import CRABAccessHistory

CRABAccessHistory.update(config.crabaccess, inventory)

LOG.info('CRABAccessHistory update completed.')

## Update: GlobalQueueRequestHistory

LOG.info('Updating GlobalQueueRequestHistory.')

from dynamo.policy.producers.globalqueue import GlobalQueueRequestHistory

GlobalQueueRequestHistory.update(config.globalqueue, inventory)

LOG.info('GlobalQueueRequestHistory update completed.')
