#!/usr/bin/python

import socket

sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sock.bind(('', 9123))
sock.listen(1)
conn, addr = sock.accept()
msg = conn.recv(1024)

conn.close()
sock.close()
