#!/bin/bash

# Copy DB table files to a backup location.
# Only works for MyISAM tables

DEFAULTSFILE=/etc/my.cnf.d/root.cnf

if ! [ -r $DEFAULTSFILE ]
then
  echo "You don't have the right permissions to perform this operation."
  exit 1
fi

DYNAMO_BASE=$(cd $(dirname $0)/..; pwd)
source $DYNAMO_BASE/etc/profile.d/init.sh

RECENT=$(date -d "12 hours ago" +%Y%m%d%H%M%S)
OLD=$(date -d "1 week ago" +%Y%m%d%H%M%S)

FIFO=/tmp/mysql-pipe.$$
mkfifo $FIFO

exec 3<>$FIFO

MYSQLCMD="mysql --defaults-file=$DEFAULTSFILE"

$MYSQLCMD < $FIFO &
MYSQL=$!
trap "rm -f $FIFO; kill -1 $MYSQL 2>&-" 0

echo "FLUSH TABLES WITH READ LOCK;" >&3

TAG=$(date +%Y%m%d%H%M%S)
NOW=$(date +"%Y:%m:%d %H:%M:%S")

for DB in dynamo dynamohistory dynamoregister dynamoserver
do
  LATEST=$(ls $DYNAMO_ARCHIVE/db/${DB}_* 2>/dev/null | tail -n 1)
  LATEST_TAG=$(echo $LATEST | sed 's/.*'$DB'_\(.*\)\.gz/\1/')
  if [ $LATEST_TAG ] && [ $LATEST_TAG -ge $RECENT ]
  then
    echo "Backup ${DB}_${LATEST_TAG} was already taken recently."
    continue
  fi

  echo "Backing up $DB.."

  cd /var/lib/mysql
  tar czO $DB/*.{frm,MYD,MYI} > $DYNAMO_ARCHIVE/db/${DB}_${TAG}.gz

  for BACKUP in $(ls $DYNAMO_ARCHIVE/db/${DB}_* 2>/dev/null)
  do
    BACKUP_TAG=$(echo $BACKUP | sed 's/.*'$DB'_\(.*\)\.gz/\1/')
    [ $BACKUP_TAG -lt $OLD ] && rm $BACKUP
  done
done

echo "UNLOCK TABLES;" >&3
exec 3>&-

echo "PURGE BINARY LOGS BEFORE '$NOW';" | $MYSQLCMD
